/* --------------------------------------------------------------------------------
 #
 #	SRPlugin.cp
 #	source generated by 4D Plugin Wizard
 #	Project : SRP
 #	author : mbs
 #	14.10.2005
 #
 # --------------------------------------------------------------------------------*/

# include	"4DPluginAPI.h"

# include	"RWString4D.h"
# include	"ExtendedExecute.h"

extern	"C"		void Yield4D (void);

# include	<stdio.h>
# include	<string.h>
# include	<memory>

#if VERSIONWIN
# include	<Windows.h>
# include 	<Mmsystem.h>

# include	<OLE2.h>
#ifndef max
#define max(a,b)            (((a) > (b)) ? (a) : (b))
#endif

#ifndef min
#define min(a,b)            (((a) < (b)) ? (a) : (b))
#endif
# include	<gdiplus.h>
using namespace	std;

HINSTANCE	gMyInstance = 0;
WCHAR		gLastFontName[32];
//ULONG_PTR	sGdiplusToken = 0;


extern "C"	BOOL __stdcall DllMain(HINSTANCE hInst, DWORD fdwReason, LPVOID lpvReserved);
BOOL __stdcall DllMain(HINSTANCE hInst, DWORD fdwReason, LPVOID lpvReserved)
{
#pragma unused (lpvReserved)

	switch (fdwReason)
	{
		case DLL_PROCESS_ATTACH:
			gMyInstance = hInst;
			return 1;
			
		case DLL_PROCESS_DETACH:
			return 0;

	  	default:
			return 1;
   	}
}
#endif

#if	__MACH__
# include	<unistd.h>
#elif	defined (__DEBUGMEM_H)
# if	__MWERKS__
#  include	<ansi_files.h>		// __close_all
#  include	<unistd.h>
# endif
#endif

//#include "AsiPort.h"

# include	"SRDataSource.h"
# include	"SRDataSourceProvider.h"
# include	"SRReportData.h"
# include	"SRReportWriter.h"
#if	WINVER
# include	"RWWinPageComposer.h"
#else
# if	MAC_OS_X_VERSION_MIN_REQUIRED < MAC_OS_X_VERSION_10_5
# include	"RWMacQDPageComposer.h"
# include	"RWMacCGPageComposer.h"
# endif
# include	"RWCTPageComposer.h"
#endif
# include	"RWReportData.h"
# include	"RWReportWriter.h"
# include	"RWBaseTypes.h"


# include	"DMReport.h"
# include	"DMArea.h"
# include	"PSObjProps.h"
# include	"SRPlugin.h"
# include	"SRLicense.h"
# include	"RW4DText.h"
# include	<sstream>

# include	"ETReportData.h"
# include	"ETReport.h"
# include	"theVersion.h"
// using namespace    FourDAPIEx;

short					gMyResFile = -1;
static	PA_Unistring*	sBuf;


FourDTypeID RW_TextToFourDTypeID (PA_PluginParameters params, int index)
{
	sBuf = PA_GetStringParameter (params, index);
	PA_Unichar*	p = PA_GetUnistring (sBuf);
	long		l = PA_GetUnistringLength (sBuf);
	return RW_TextToFourDTypeID (p , l);
}


FourDTypeID RW_TextToFourDTypeID (PA_Unichar* p, long l)
{
	OSType		result = '    ';

	if (l > 4)
		l = 4;
	while (l > 0 && *p >= ' ' && *p <= 255)
	{
		result = (result << 8) | (*p & 0xFF);
		p++;
		l--;
	}

	return result;
}


PA_Unichar* RW_FourDTypeIDToText (OSType l)
{
	static	PA_Unichar	r [5];

	r [4] = 0;
	int	i;
	for (i = 4; l != 0 && i-- > 0; )
	{
		r [i] = l & 0xff;
		l >>= 8;
	}

	return &r [i];
}


//static	PA_Unichar		emptyStr[1] = {	0 };

void PluginMain (PA_long32 selector, PA_PluginParameters params )
{
try
{
	long	obj = 0;

	if (selector > eRWArea && selector != eDeleteReport && selector != eCloseSession)
	{
		if (eLicense_ExpiredBeta == RW_GetLicense())
			return;
	}

	switch( selector )
	{
		case kInitPlugin:
			InitPlugin();
			break;

		case kDeinitPlugin:
			DeinitPlugin();
			break;


		case eOpenSession:			//	outSession, RW_Flags, ".pdf", template, job name, printer
		{
			sBuf = PA_GetStringParameter (params, 3);
			CText	s3 = RWStr::FromPA (sBuf);
			sBuf = PA_GetStringParameter (params, 4);
			CText	s4 = RWStr::FromPA (sBuf);
			sBuf = PA_GetStringParameter (params, 5);
			CText	s5 = RWStr::FromPA (sBuf);
			sBuf = PA_GetStringParameter (params, 6);	//mbs 25072011	printer
			CText	s6 = RWStr::FromPA (sBuf);
			PA_ReturnLong (params, RW_OpenSession (obj, PA_GetLongParameter (params, 2), s3, s4, s5, s6));
			PA_SetLongParameter (params, 1, obj);
			break;
		}

		case eCloseSession:			//	ioSession
		{
			obj = PA_GetLongParameter (params, 1);
			PA_ReturnLong (params, RW_CloseSession (obj));
			PA_SetLongParameter (params, 1, obj);
			break;
		}

		case ePrintSRP:				//	".srxml", SR_Flags, RW_Flags, ".pdf", session, printer
		{
			sBuf = PA_GetStringParameter (params, 1);
			CText	s1 = RWStr::FromPA (sBuf);
			sBuf = PA_GetStringParameter (params, 4);
			CText	s4 = RWStr::FromPA (sBuf);
			sBuf = PA_GetStringParameter (params, 6);	//mbs 25072011	printer
			CText	s6 = RWStr::FromPA (sBuf);
			PA_ReturnLong (params, RW_Print (s1, PA_GetLongParameter (params, 2), PA_GetLongParameter (params, 3), s4, PA_GetLongParameter (params, 5), s6));
			break;
		}

		case eProcessSRP:			//	".srxml", SR_Flags, ".rwxml"
		{
			sBuf = PA_GetStringParameter (params, 1);
			CText	s1 = RWStr::FromPA (sBuf);
			sBuf = PA_GetStringParameter (params, 3);
			CText	s2 = RWStr::FromPA (sBuf);
			PA_ReturnLong (params, RW_Process_RW (s1, PA_GetLongParameter (params, 2), s2));
			break;
		}

		case ePrintRW:				//	".rwxml", Ignored_Flags, RW_Flags, ".pdf", session, printer
		{
			sBuf = PA_GetStringParameter (params, 1);
			CText	s1 = RWStr::FromPA (sBuf);
			sBuf = PA_GetStringParameter (params, 4);
			CText	s4 = RWStr::FromPA (sBuf);
			sBuf = PA_GetStringParameter (params, 6);	//mbs 25072011	printer
			CText	s6 = RWStr::FromPA (sBuf);
			PA_ReturnLong (params, RW_Print_RW (s1, PA_GetLongParameter (params, 2), PA_GetLongParameter (params, 3), s4, PA_GetLongParameter (params, 5), s6));
			break;
		}



		case eRegister:				//	license
		{
			sBuf = PA_GetStringParameter (params, 1);
			CText	s1 = RWStr::FromPA (sBuf);
			if (!s1.empty()) {
				(void) RW_SetLicense (s1);
				PA_ReturnLong (params, RW_GetLicense());
			} else {
				s1 = RWStr::Format ("%ld", (long) PA_GetSerialKey());
				RWStr::SetPA (sBuf, s1);
				PA_ReturnLong (params, RW_GetLicense());
			}
			break;
		}

		case eRWArea:
			RW_Area (params);
			break;

		case eNewReport:			//	ref, "srxml", options (bit 0 means path vs. XML)
		{
			sBuf = PA_GetStringParameter (params, 2);
			CText	s2 = RWStr::FromPA (sBuf);
			PA_ReturnLong (params, RW_CreateReport (obj, s2, PA_GetLongParameter (params, 3)));
			PA_SetLongParameter (params, 1, obj);
			break;
		}
			
		case eParseReport:			//	ref, "srxml", options (bit 0 means path vs. XML)
		{
			sBuf = PA_GetStringParameter (params, 2);
			CText	s2 = RWStr::FromPA (sBuf);
			PA_ReturnLong (params, RW_ParseReport (PA_GetLongParameter (params, 1), s2, PA_GetLongParameter (params, 3)));
			break;
		}

		case eSaveReport:			//	ref, "srxml", options (bit 0 means path vs. XML)
		{
			sBuf = PA_GetStringParameter (params, 2);
			CText	s2 = RWStr::FromPA (sBuf);
			PA_ReturnLong (params, obj = RW_SaveReport (PA_GetLongParameter (params, 1), s2, PA_GetLongParameter (params, 3)));
			//mbs 25042010	save the string if XML is requested...
			if (obj == 0 && (PA_GetLongParameter (params, 3) & 0x1) == 0)
				RWStr::SetPA (sBuf, s2);
			break;
		}

		case eDeleteReport:			//	ref
		{
			obj = PA_GetLongParameter (params, 1);
			PA_ReturnLong (params, RW_DeleteReport (obj));
			PA_SetLongParameter (params, 1, obj);
			break;
		}


		case eGetProperties:		//	repRef, ref, properties, values
			PA_ReturnLong (params, RW_GetProperties (params));
			break;

		case eSetProperties:		//	repRef, ref, properties, values
			PA_ReturnLong (params, RW_SetProperties (params));
			break;

		case eGetProperty:			//	repRef, ref, propertyID, value
		{
			PA_Pointer	ptr = PA_GetPointerParameter (params, 4);
			PA_ReturnLong (params,
				RW_GetProperty (
					PA_GetLongParameter (params, 1),
					PA_GetLongParameter (params, 2),
					RW_TextToFourDTypeID (params, 3),
					ptr));
			break;
		}

		case eSetProperty:			//	repRef, ref, propertyID, value
		{
			PA_Pointer	ptr = PA_GetPointerParameter (params, 4);
			PA_ReturnLong (params,
				RW_SetProperty (
					PA_GetLongParameter (params, 1),
					PA_GetLongParameter (params, 2),
					RW_TextToFourDTypeID (params, 3),
					ptr));
			break;
		}

		case eGetObjects:			//	repRef, ref, propertyID, value
		{
			PA_Variable	var = PA_GetVariableParameter (params, 4);
			PA_ReturnLong (params,
				RW_GetObjects (
					PA_GetLongParameter (params, 1),
					PA_GetLongParameter (params, 2),
					RW_TextToFourDTypeID (params, 3),
					var));
			PA_SetVariableParameter (params, 4, var, false);
			break;
		}


		case eNewObject:			//	repRef, ref, propertyID, parent
		{
			PA_ReturnLong (params,
				RW_NewObject (
					PA_GetLongParameter (params, 1),
					obj,
					RW_TextToFourDTypeID (params, 3),
					PA_GetLongParameter (params, 4)));
			PA_SetLongParameter (params, 2, obj);
			break;
		}

		case eDeleteObject:			//	repRef, ref
		{
			obj = PA_GetLongParameter (params, 2);
			PA_ReturnLong (params, RW_DeleteObject (PA_GetLongParameter (params, 1), obj));
			PA_SetLongParameter (params, 2, obj);
			break;
		}

		case eChangeObjectParent:	//	repRef, ref, newParentRef
			PA_ReturnLong (params, RW_ChangeObjectParent (PA_GetLongParameter (params, 1), PA_GetLongParameter (params, 2), PA_GetLongParameter (params, 3)));
			break;
			
		case eGetObjectXML:			//	repRef, ref, XML
		{
			CText	xml;
			PA_ReturnLong (params, RW_GetObjectXML (PA_GetLongParameter (params, 1), PA_GetLongParameter (params, 2), xml));
			sBuf = PA_GetStringParameter (params, 3);
			RWStr::SetPA (sBuf, xml);
			break;
		}
			
		case eNewObjectFromXML:		//	repRef, ref, XML, parent
		{
			sBuf = PA_GetStringParameter (params, 3);
			CText	xml = RWStr::FromPA (sBuf);
			PA_ReturnLong (params, RW_NewObjectFromXML (PA_GetLongParameter (params, 1), obj, xml, PA_GetLongParameter (params, 4)));
			PA_SetLongParameter (params, 2, obj);
			break;
		}

		case eFindObjectByID:		//	repRef, name, ref
		{
			sBuf = PA_GetStringParameter (params, 2);
			CText	s1 = RWStr::FromPA (sBuf);
			PA_ReturnLong (params, RW_FindObjectByID (PA_GetLongParameter (params, 1), s1, obj));
			PA_SetLongParameter (params, 3, obj);
			break;
		}

		case eGetParent:			//	repRef, ref, parent
		{
			PA_ReturnLong (params, RW_GetParent (PA_GetLongParameter (params, 1), PA_GetLongParameter (params, 2), obj));
			PA_SetLongParameter (params, 3, obj);
			break;
		}

		case eGetObjectRect:		//	repRef, ref, rect
		{
			SRect	rect;
			PA_ReturnLong (params, RW_GetObjectRect (PA_GetLongParameter (params, 1), PA_GetLongParameter (params, 2), rect));
			PA_SetDoubleParameter (params, 4, rect.top);
			PA_SetDoubleParameter (params, 3, rect.left);
			PA_SetDoubleParameter (params, 6, rect.bottom);
			PA_SetDoubleParameter (params, 5, rect.right);
			break;
		}
			
		case eSaveUndo:				//	repRef, operation
			PA_ReturnLong (params, RW_SaveUndo (PA_GetLongParameter (params, 1), PA_GetLongParameter (params, 2)));
			break;
			
		case eAddUndoSnapshot:		//	repRef, ref, old
			PA_ReturnLong (params, RW_AddUndoSnapshot (PA_GetLongParameter (params, 1), PA_GetLongParameter (params, 2), PA_GetLongParameter (params, 3)));
			break;
			
		case eDoUndo:				//	repRef
			PA_ReturnLong (params, RW_DoUndo (PA_GetLongParameter (params, 1)));
			break;
			
		case eDoRedo:				//	repRef
			PA_ReturnLong (params, RW_DoRedo (PA_GetLongParameter (params, 1)));
			break;
			
		case ePrintSettings:		//	repRef, options
			PA_ReturnLong (params, RW_PrintSettings (PA_GetLongParameter (params, 1), PA_GetLongParameter (params, 2)));
			break;

		case eTextStyleAdd:			//	outStr, inStr, from, to, style, fontName, fontSize, fontColor, setColor, scale, rounding, mode
			PA_ReturnLong (params, RW_AddRemoveStyle (params, true));
			break;

		case eTextStyleRemove:		//	outStr, inStr, from, to, style, fontName, fontSize, fontColor, setColor, scale, rounding,
			PA_ReturnLong (params, RW_AddRemoveStyle (params, false));
			break;

		case eTextStyleAddStyle:	//	outStr, inStr, from, to, inRepRef, styleID, scale, rounding
			PA_ReturnLong (params, RW_ApplyStyle (params));
			break;

		case eTokenize:				//	inStr, blob, returns length
		{
			sBuf = PA_GetStringParameter (params, 1);
			long	len = PA_Tokenize (sBuf, 0);
			char *	tokens = new char [len];
			len = PA_Tokenize (sBuf, tokens);
			PA_SetBlobParameter (params, 2, tokens, len);
			delete [] tokens;
			PA_ReturnLong (params, len);
			break;
		}

		case eDetokenize:			//	inBlob, returns text
		{
			char *	tokens = NULL;
			long	len = PA_GetBlobParameter (params, 1, tokens);
			tokens = new char [len];
			len = PA_GetBlobParameter (params, 1, tokens);
			PA_Unistring method = PA_Detokenize (tokens, len);
			delete [] tokens;
			PA_ReturnString (params, PA_GetUnistring (&method));
			PA_DisposeUnistring (&method);
			break;
		}

		case eRunScript:			//	inStr
		{
			sBuf = PA_GetStringParameter (params, 1);
			ExtendedExecute	ee (PA_GetUnistring (sBuf), PA_GetUnistringLength (sBuf));
			 // ee.Init();
			ee.Execute();
			break;
		}
	
		case eVersionString:			//	inStr
		{
			CText			version = RWStr::FromASCII (kVersionString);
			PA_Unistring	versString = RWStr::CreatePA (version);
			PA_ReturnString (params, PA_GetUnistring (&versString));
			PA_DisposeUnistring(&versString);
			break;
		}
		
		case eGetEditorRect:		//	repRef,  rect
		{
			SRect	rect;
			PA_ReturnLong (params, RW_GetEditorRect (PA_GetLongParameter (params, 1), rect));
			PA_SetDoubleParameter (params, 2, rect.left);
			PA_SetDoubleParameter (params, 3, rect.top);
			PA_SetDoubleParameter (params, 4, rect.right);
			PA_SetDoubleParameter (params, 5, rect.bottom);
			break;
		}
		
		case eSetScriptExecution:		//	repRef,  rect
		{
			SRect	rect;
			PA_ReturnLong (params, RW_ExecuteScript(PA_GetLongParameter (params, 1)));
			break;
		}
		
		case eGetFonts:		//	array
		{
			PA_Variable	var = PA_GetVariableParameter (params, 1);
			PA_ReturnLong (params, RW_GetFonts( var ));
			PA_SetVariableParameter (params, 1, var, false);
			break;
		}
			
/*
		case eLast:	//	picture, arrayT, blob
		{
			PA_Variable	var = PA_GetVariableParameter (params, 2);
			if (PA_GetVariableKind (var) != eVK_ArrayUnicode)
				PA_ReturnLong (params, errInvalidArrayType);
			else
			{
				PA_Picture	p = PA_GetPictureParameter (params, 1);
				PA_Variable	v2[2];
				memset (&v2, 0, sizeof (v2));
				long	index = 1;
				while (true)
				{
					PA_Unistring	u = PA_GetPictureData (p, index, NULL);
					if (PA_GetLastError() != 0)
						break;
					PA_DisposeUnistring (&u);
					index++;
				}
				PA_ResizeArray (&var, index - 1);
				index = 1;
				while (true)
				{
					PA_Unistring	u = PA_GetPictureData (p, index, NULL);
					if (PA_GetLastError() != 0)
						break;
					PA_SetStringInArray (var, index, &u);
					index++;
				}
				v2[0].fType = eVK_Picture;
				v2[0].uValue.fPicture = p;
				v2[1] = PA_CreateVariable (eVK_Blob);
				PA_Variable	result = PA_ExecuteCommandByID (532, v2, 2);	// VARIABLE TO BLOB
				PA_ReturnLong (params, index - 1);
				PA_SetVariableParameter (params, 2, var, false);
				PA_SetBlobHandleParameter (params, 3, PA_GetBlobHandleVariable (v2[1]));
				PA_ClearVariable (&result);
			}
			break;
		}
			
		case eLast + 1:	//	blob -> picture
		{
			long	size = PA_GetBlobParameter (params, 1, NULL);
			char	*store = new char [size];
			size = PA_GetBlobParameter (params, 1, store);
			PA_Picture	p = PA_CreatePicture (store, size);
			PA_ReturnPicture (params, p);
			void	*ps = PA_CreateNativePictureForScreen (p);
			void	*pp = NULL;
			#if	WINVER
				pp = PA_CreateNativePictureForPrinting (p);
				if (ps)
					delete reinterpret_cast <Gdiplus::Bitmap*> (ps);
				if (pp)
					delete reinterpret_cast <Gdiplus::Metafile*> (pp);
			#else
//				pp = PA_CreateNativePictureForPrinting (p);		- hard crash in 4D
				if (ps)
					::CFRelease (reinterpret_cast <CGImageRef> (ps));
				if (pp)
					::CFRelease (reinterpret_cast <CGPDFDocumentRef> (pp));
			#endif
			break;
		}
*/
	}
}
catch (...)
{
	printf ("\nUncaught exception in PluginMain!!! selector = %ld\n", selector);
	fflush (stdout);
}
}


# pragma	mark -

#if	WINVER__
# include	<OLE2.h>
# include	<gdiplus.h>
#endif

void InitPlugin (void)
{
# if	_USE_MAC_API_
	gMyResFile = ::CurResFile();
# endif

//	PA_UseCStrings();
//	PA_ReturnNullTerminatedText (false);


#ifdef	__DEBUGMEM_H

	// DebugMemTurnOptionsOn (dgbmemOptDontFreeBlocks);
	DebugMemForgetLeaks();
	DebugMemReadLeaks ("rw.log");
#endif

#if	WINVER__
   // Initialize GDI+.
   Gdiplus::GdiplusStartupInput gdiplusStartupInput;
   Gdiplus::GdiplusStartup (&sGdiplusToken, &gdiplusStartupInput, NULL);
#endif

	RW_SetLicense (RWString());
}


void DeinitPlugin (void)
{
#if	WINVER__
   // Terminate GDI+.
   Gdiplus::GdiplusShutdown (sGdiplusToken);
#endif

#ifdef	__DEBUGMEM_H
# if	__MWERKS__ && !__MACH__
	__close_all();
# endif


#if !VERSIONWIN
	UTEC::Free();
#endif

	size_t	leaks = DebugMemReportLeaks ("rw.log");
	if (leaks != 0)
	{
		printf ("\nLeaked memory: %ld bytes\n", (long) leaks);
		fflush (stdout);
	}
#endif
}



long RW_OpenSession (long &outSession, long dstFlags, CText &dst, CText &inTemplate, CText &job, CText &inPrinter)	//mbs 25072011	printer
{
	RWPageComposer	*session = NULL;
	//mbs 08102010	needs to parse report template BEFORE opening the session!!!
	//mbs 19012011	needs to set job name BEFORE opening the session!!!
	long	result = RWPageComposer::OpenSession (session, dstFlags, inTemplate, dst, job, inPrinter);	//mbs 25072011	printer
    if(session != NULL)
        outSession = session->GetInternalID();
    else
        outSession = 0;
	return result;
}


long RW_CloseSession (long &ioSession)
{
	RWPageComposer	*session = RWPageComposer::GetSessionObject (ioSession);
	if (session == NULL)
		return errInvalidSessionRef;
	RWPageComposer::CloseSession (session);
	ioSession = 0;
	return noErr;
}


# define	IsFileName	((inOptions & 0x1) != 0)

// ---------------------------------------------------------------------------
// LoadSourceXML
// ---------------------------------------------------------------------------
// A report comes as a 4D document path (inIsFileName) or as XML text.

static	long	LoadSourceXML (RWXmlDocument &outXML, const CText &inSource, bool inIsFileName)
{
	RWXmlResult	result = inIsFileName ? outXML.LoadFile (RWStr::NativePath (inSource)) : outXML.LoadString (inSource);
	if (!result)
	{
		if (inIsFileName)
			printf ("Could not load file '%s'. Error='%s'.\n", RWStr::ToUTF8 (RWStr::NativePath (inSource)).c_str(), RWStr::ToUTF8 (result.description).c_str());
		else
			printf ("Could not load XML. Error='%s' at offset %ld.\n", RWStr::ToUTF8 (result.description).c_str(), (long) result.offset);
		fflush (stdout);
		return errCantLoadXML;
	}
	return noErr;
}

// source description for error messages: the path, or just "XML text"
static	std::string	SourceName (const CText &inSource, bool inIsFileName)
{
	return inIsFileName ? RWStr::ToUTF8 (RWStr::NativePath (inSource)) : std::string ("XML text");
}


long RW_Print (CText &src, long inOptions, long dstFlags, CText &dst, long inSession, CText &inPrinter)	//mbs 25072011	printer
{
	RWPageComposer	*session = NULL;
	if (inSession != 0)
	{
		session = RWPageComposer::GetSessionObject (inSession);
		if (session == NULL)
			return errInvalidSessionRef;
	}

	long					result = 0;

	try
	{
		RWXmlDocument	xml;
		result = LoadSourceXML (xml, src, IsFileName);

		if (result == noErr)
		{
			SRReportData					reportData (&xml);
			SRDataSource					reportSource;
			std::unique_ptr<RWXmlDocument>	printed;
			{
				SRReportWriter	reporter (reportSource, reportData, inOptions);
				printed = reporter.ReportToXML();
			}
			if (printed)
			{
				if (dstFlags & 0x10000000)	// debugging: keep the processed report next to the output
					(void) printed->SaveFile (RWStr::NativePath (dst) + u".rwxml");

				std::unique_ptr<RWPageComposer>	arwComposer;
				RWPageComposer	*pc = session;
				if (session == NULL)
				{
					pc = RWPageComposer::CreatePrinterComposer (dstFlags, dst, inPrinter);	//mbs 25072011	printer
					arwComposer.reset (pc);
				}
				else
					session->IncreaseBatchLevel();

				try
				{
					RWReportData		rwData (printed.get());
					RWReportWriter		rwReport (reportSource, rwData, *pc);
					rwReport.Report (NULL);
					result = rwReport.GetLastError();
					if (session != NULL)
						session->DecreaseBatchLevel();
				}
				catch (...)
				{
					if (session != NULL)
						session->DecreaseBatchLevel();
					throw;
				}
			}
		}
	}
	catch (long l)
	{
		printf ("\nException in RW_Print: %ld. Source: %s\n", l, SourceName (src, IsFileName).c_str());
		fflush (stdout);
		result = l;
	}
	catch (...)
	{
		printf ("\nUncaught exception in RW_Print! Source: %s\n", SourceName (src, IsFileName).c_str());
		fflush (stdout);
		result = errGenericError;
	}

	return result;
}


long RW_Process_RW (CText &src, long inOptions, CText &dst)
{
	long	result = 0;

	try
	{
		RWXmlDocument	xml;
		result = LoadSourceXML (xml, src, IsFileName);

		if (result == noErr)
		{
			const RWString	path = RWStr::NativePath (dst);
			SRReportData	reportData (&xml);
			SRDataSource	reportSource;
			bool			saved = false;

			//mbs 05112010
			if ((inOptions & ~1) != 0)	// non-zero options (except path) means export
			{
				std::unique_ptr<RWXmlDocument>	printed;
				{
					SRReportWriter	reporter (reportSource, reportData, inOptions);
					printed = reporter.ReportToXML();
				}
				if (printed)
				{
					ETReportData	etData (printed.get());
					ETReport		etReport (reportSource, etData, inOptions);
					saved = etReport.ReportToFile (path);
				}
			}
			else
			{
				SRReportWriter					reporter (reportSource, reportData, inOptions);
				std::unique_ptr<RWXmlDocument>	printed = reporter.ReportToXML();
				saved = printed && printed->SaveFile (path);
			}

			if (!saved)
			{
				printf ("Could not create RW file '%s'. Error='%s'.\n", RWStr::ToUTF8 (path).c_str(), strerror (errno));
				fflush (stdout);
				result = errCantSaveXML;
			}
		}
	}
	catch (long l)
	{
		printf ("\nException in RW_Process_RW: %ld. Source: %s\n", l, SourceName (src, IsFileName).c_str());
		fflush (stdout);
		result = l;
	}
	catch (...)
	{
		printf ("\nUncaught exception in RW_Process_RW! Source: %s\n", SourceName (src, IsFileName).c_str());
		fflush (stdout);
		result = errGenericError;
	}

	return result;
}


long RW_Print_RW (CText &src, long inOptions, long dstFlags, CText &dst, long inSession, CText &inPrinter)	//mbs 25072011	printer
{
	RWPageComposer	*session = NULL;
	if (inSession != 0)
	{
		session = RWPageComposer::GetSessionObject (inSession);
		if (session == NULL)
			return errInvalidSessionRef;
	}

	long	result = 0;

	try
	{
		RWXmlDocument	xml;
		result = LoadSourceXML (xml, src, IsFileName);

		if (result == noErr)
		{
			std::unique_ptr<RWPageComposer>	arwComposer;
			RWPageComposer	*pc = session;
			if (session == NULL)
			{
				pc = RWPageComposer::CreatePrinterComposer (dstFlags, dst, inPrinter);	//mbs 25072011	printer
				arwComposer.reset (pc);
			}
			else
				session->IncreaseBatchLevel();

			try
			{
				SRDataSourceProvider	reportSource;
				RWReportData			rwData (&xml);
				RWReportWriter			rwReport (reportSource, rwData, *pc);
				rwReport.Report (NULL);
				if (session != NULL)
					session->DecreaseBatchLevel();
			}
			catch (...)
			{
				if (session != NULL)
					session->DecreaseBatchLevel();
				throw;
			}
		}
	}
	catch (long l)
	{
		printf ("\nException in RW_Print_RW: %ld. Source: %s\n", l, SourceName (src, IsFileName).c_str());
		fflush (stdout);
		result = l;
	}
	catch (...)
	{
		printf ("\nUncaught exception in RW_Print_RW! Source: %s\n", SourceName (src, IsFileName).c_str());
		fflush (stdout);
		result = errGenericError;
	}

	return result;
}


# pragma	mark -


static			unsigned long	myYieldTicks = 0;
//static	const	unsigned long	myYieldDelta = 10;
static			unsigned long	myYieldDelta = 10;

extern	"C"		void Yield4D (void)
{
    /*
#if	MACVER
	unsigned long	ticks = (unsigned long) TickCount();
	if (ticks < myYieldTicks)	// time wrap
		myYieldTicks = 0;
	if (ticks > myYieldTicks + myYieldDelta)
	{
		myYieldTicks = ticks;
		PA_Yield();
	}
#else
	unsigned long	ticks = (unsigned long) ::timeGetTime() * 14;
	if (ticks < myYieldTicks)	// time wrap
		myYieldTicks = 0;
	if (ticks > myYieldTicks + myYieldDelta)
	{
		myYieldTicks = ticks;
		PA_Yield();
	}
#endif
     */
}


void	RW_RunInMainThread (RW_CBFunction inFunction, void *inData)
{
	if (PA_GetCurrentProcessNumber() == 0)
		inFunction (inData);
	else
		PA_RunInMainProcess (inFunction, inData);
}


void	RW_ConvertPictureForPrinting (RWValue &ioPict, bool inForPDF)
{
	if (ioPict.GetBlobSize() > 0)
	{
		PA_Picture	p = SR4DData::Get4DPicture (ioPict);
		if (p)
		{
			if (inForPDF)
				SR4DData::GetPictureFrom4D (p, ioPict, inForPDF);
			else
			{
#if	1
				ioPict.SetPictureRef (PA_CreateNativePictureForPrinting (p), false);	// this will crash on Mac 4D 11.6
#else
				if (PA_GetShort4DVersion() >= 0x1200)	// try it on 4D v19
					ioPict.SetPictureRef (PA_CreateNativePictureForPrinting (p), false);
				else
# if	1
					ioPict.SetPictureRef (PA_CreateNativePictureForScreen (p), true);
# else
					SR4DData::GetPictureFrom4D (p, ioPict, true);
# endif
#endif
			}
			PA_DisposePicture (p);
		}
	}
}


#pragma	mark	-


void RW_Area (PA_PluginParameters params)
{
	try
	{
		DMArea::HandleEvent (params);
	}
	catch (...)
	{
		printf ("\nUncaught exception in RW_Area!\n");
		fflush (stdout);
	}

	return;
}


long RW_CreateReport (long &outRepRef, CText &src, long inOptions)
{
	long		result = 0;
	DMReport	*rep = NULL;

	try
	{
		if (!src.empty())
		{
			RWXmlDocument	xml;
			result = LoadSourceXML (xml, src, IsFileName);
			if (result == noErr)
				rep = new DMReport (&xml);
		}
		else
			rep = new DMReport (NULL);
		outRepRef = rep ? rep->GetInternalID() : 0;
	}
	catch (...)
	{
		printf ("\nUncaught exception in RW_CreateReport!\n");
		fflush (stdout);
		result = errGenericError;
		if (rep)
			delete rep;
	}

	return result;
}


long RW_ParseReport (long inRepRef, CText &src, long inOptions)
{
	long		result = 0;

	try
	{
		DMReport	*rep = DMReport::GetReportObject (inRepRef);
		if (rep == NULL)
			result = errInvalidReportRef;
		else if (!src.empty())
		{
			RWXmlDocument	xml;
			result = LoadSourceXML (xml, src, IsFileName);
			if (result == noErr)
				rep->SetReport (&xml);
		}
		else
			rep->SetReport (NULL);
	}
	catch (...)
	{
		printf ("\nUncaught exception in RW_ParseReport!\n");
		fflush (stdout);
		result = errGenericError;
	}

	return result;
}


// the report is written to the file src (inOptions bit 0), or returned in src as XML text
long RW_SaveReport (long inRepRef, CText &src, long inOptions)
{
	long		result = 0;

	try
	{
		DMReport	*rep = DMReport::GetReportObject (inRepRef);
		if (rep == NULL)
			result = errInvalidReportRef;
		else
		{
			RWXmlDocument	xml;
			rep->GetReport (xml);
			if (IsFileName)
			{
				const RWString	path = RWStr::NativePath (src);
				if (!xml.SaveFile (path))
				{
					printf ("Could not save file '%s'. Error='%s'.\n", RWStr::ToUTF8 (path).c_str(), strerror (errno));
					fflush (stdout);
					result = errCantSaveXML;
				}
			}
			else
				src = xml.SaveString (false, true);
		}
	}
	catch (...)
	{
		printf ("\nUncaught exception in RW_SaveReport!\n");
		fflush (stdout);
		result = errGenericError;
	}

	return result;
}
# undef	IsFileName


long RW_DeleteReport (long &ioRepRef)
{
	long		result = 0;

	try
	{
		DMReport	*rep = DMReport::GetReportObject (ioRepRef);
		if (rep == NULL || dynamic_cast <DMArea*> (rep) != NULL)	// must not destroy area!
			result = errInvalidReportRef;
		else
		{
			ioRepRef = 0;
			delete rep;
		}
	}
	catch (...)
	{
		printf ("\nUncaught exception in RW_DeleteReport!\n");
		fflush (stdout);
		result = errGenericError;
	}

	return result;
}


long RW_GetProperties (PA_PluginParameters params)	// inRepRef, inRef, PA_Variable &ioProps, PA_Variable &ioValues);
{
	long		result = 0;
	DMReport	*rep = DMReport::GetReportObject (PA_GetLongParameter (params, 1));
	if (rep == NULL)
		result = errInvalidReportRef;
	else
	{
		long		inRef = PA_GetLongParameter (params, 2);
		DMBase		*obj = NULL;
		if (inRef != 0)
		{
			obj = rep->GetObject (inRef);
			if (obj == NULL)
				result = errInvalidObjectRef;
		}
		if (result == 0)
		{
			const DMBase::UserProps	*prs;
			PA_Variable	props = PA_GetVariableParameter (params, 3);
			PA_Variable	vals = PA_GetVariableParameter (params, 4);
			PA_Variable	names = PA_GetVariableParameter (params, 5);
			if (PA_GetVariableKind (props) != eVK_ArrayUnicode || PA_GetVariableKind (vals) != eVK_ArrayUnicode)
				result = errInvalidArrayType;
			else
			{
				int		i;
				long	count, realCount = 0;
				bool	useNames = (PA_GetVariableKind (names) == eVK_ArrayUnicode);
				if (obj == NULL)	// selected objects
				{
					std::unique_ptr<PSObjList>	l (rep->GetObjects (PSObjPropSelected));
					if (l->size() == 0)
						result = errInvalidObjectRef;
					else if (l->size() == 1)
						obj = static_cast <DMBase*> (*l->begin());
					else if (l->size() > 1)
					{
						obj = static_cast <DMBase*> (*l->begin());
						count = obj->GetUserProperties (prs);
						PSPropsMap	propsmap;
						RWValue	rv;
						for (i = 1; prs->id; prs++, i++)
						{
							if (static_cast <PSObject*> (obj)->GetProperty (prs->id, rv))
							{
								propsmap.SetProperty (prs->id, rv);
								realCount++;
							}
						}
						PSObjList::iterator		iter;
						OSType					id;
						for (iter = l->begin() + 1; iter != l->end(); iter++)
						{
							obj = static_cast <DMBase*> (*iter);
							count = obj->GetUserProperties (prs);
							for (i = 1; prs->id; prs++, i++)
							{
								if (static_cast <PSObject*> (obj)->GetProperty (prs->id, rv))
								{
									RWValue	mrv;
									if (propsmap.GetPropertyRef (prs->id, mrv))
									{
										if (mrv == rv)	// same value for this property?
											;	// nothing to do
										else
										{
											mrv.SetText (u"<multiple values>");
											propsmap.SetProperty (prs->id, mrv);
										}
									}
								}
								else if (propsmap.RemoveProperty (prs->id))
									realCount--;
							}
							PSPropsMap::reverse_iterator	rit;
							for (rit = propsmap.rbegin(); rit != propsmap.rend(); rit++)
							{
								id = (*rit).first;
								if (PSObject::FindPropertyByID (id, obj->GetProperties()) == NULL)
									if (propsmap.RemoveProperty (id))
										realCount--;
							}
						}

						obj = static_cast <DMBase*> (*l->begin());
						count = realCount;
						realCount = 0;
						PA_ResizeArray (&props, count);
						PA_ResizeArray (&vals, count);
						if (useNames)
							PA_ResizeArray (&names, count);
						count = obj->GetUserProperties (prs);
						for (i = 1; prs->id; prs++, i++)
						{
							if (propsmap.GetPropertyRef (prs->id, rv))
							{
								realCount++;
								RWTextValue	value;
								rv.GetTextValue (value, NULL);
								PA_Unistring	ustr = PA_CreateUnistring (RW_FourDTypeIDToText (prs->id));
								PA_SetStringInArray (props, realCount, &ustr);
								ustr = RWStr::CreatePA (value);
								PA_SetStringInArray (vals, realCount, &ustr);
								if (useNames)
								{
									const PSObject::PSObjProps *ps = PSObject::FindPropertyByID (prs->id, obj->GetProperties());
									if (ps && ps->name && *ps->name)
									{
										CText	n = RWStr::FromUTF8 (ps->name);
										ustr = RWStr::CreatePA (n);
									}
									else
										ustr = PA_CreateUnistring (RW_FourDTypeIDToText (prs->id));
									PA_SetStringInArray (names, realCount, &ustr);
								}
							}
						}
						if (realCount < count)
						{
							PA_ResizeArray (&props, realCount);
							PA_ResizeArray (&vals, realCount);
							if (useNames)
								PA_ResizeArray (&names, realCount);
						}
						PA_SetVariableParameter (params, 3, props, false);
						PA_SetVariableParameter (params, 4, vals, false);
						if (useNames)
							PA_SetVariableParameter (params, 5, names, false);
						obj = NULL;
					}
				}
				if (obj != NULL)	// this object
				{
					count = obj->GetUserProperties (prs);
					PA_ResizeArray (&props, count);
					PA_ResizeArray (&vals, count);
					if (useNames)
						PA_ResizeArray (&names, count);
					for (i = 1; prs->id; prs++, i++)
					{
						RWTextValue	value;
						if (static_cast <PSObject*> (obj)->GetProperty (prs->id, value))
						{
							realCount++;
							PA_Unistring	ustr = PA_CreateUnistring (RW_FourDTypeIDToText (prs->id));
							PA_SetStringInArray (props, realCount, &ustr);
							ustr = RWStr::CreatePA (value);
							PA_SetStringInArray (vals, realCount, &ustr);
							if (useNames)
							{
								const PSObject::PSObjProps *ps = PSObject::FindPropertyByID (prs->id, obj->GetProperties());
								if (ps && ps->name && *ps->name)
								{
									CText	n = RWStr::FromUTF8 (ps->name);
									ustr = RWStr::CreatePA (n);
								}
								else
									ustr = PA_CreateUnistring (RW_FourDTypeIDToText (prs->id));
								PA_SetStringInArray (names, realCount, &ustr);
							}
						}
					}
					if (realCount < count)
					{
						PA_ResizeArray (&props, realCount);
						PA_ResizeArray (&vals, realCount);
						if (useNames)
							PA_ResizeArray (&names, realCount);
					}
					PA_SetVariableParameter (params, 3, props, false);
					PA_SetVariableParameter (params, 4, vals, false);
					if (useNames)
						PA_SetVariableParameter (params, 5, names, false);
				}
			}
		}
	}

	return result;
}


long RW_SetProperties (PA_PluginParameters params)	// inRepRef, inRef, PA_Variable &inProps, PA_Variable &inValues);
{
	long		result = 0;
	DMReport	*rep = DMReport::GetReportObject (PA_GetLongParameter (params, 1));
	if (rep == NULL)
		result = errInvalidReportRef;
	else
	{
		long		inRef = PA_GetLongParameter (params, 2);
		DMBase		*obj = NULL;
		if (inRef != 0)
		{
			obj = rep->GetObject (inRef);
			if (obj == NULL)
				result = errInvalidObjectRef;
		}
		if (result == 0)
		{
			PA_Variable	props = PA_GetVariableParameter (params, 3);
			PA_Variable	vals = PA_GetVariableParameter (params, 4);
			if (PA_GetVariableKind (props) != eVK_ArrayUnicode || PA_GetVariableKind (vals) != eVK_ArrayUnicode)
				result = errInvalidArrayType;
			else
			{
				DMArea	*area = NULL;
				if (rep->GetPageComposer() != NULL)
					area = static_cast <DMArea*> (rep);
				int		i;
				long	count = PA_GetArrayNbElements (props);
				if (obj == NULL)	// selected objects
				{
					std::unique_ptr<PSObjList>	l (rep->GetObjects (PSObjPropSelected));
					if (l->size() == 0)
						result = errInvalidObjectRef;
					else if (l->size() == 1)
						obj = static_cast <DMBase*> (*l->begin());
					else if (l->size() > 1)
					{
						for (i = 1; i < count; i++)
						{
							PA_Unistring	ustr = PA_GetStringInArray (vals, i);
							RWValue			value;
							value.SetText (RWStr::FromPA (&ustr));
							ustr = PA_GetStringInArray (props, i);
							OSType	id = RW_TextToFourDTypeID (PA_GetUnistring (&ustr), PA_GetUnistringLength (&ustr));
							RWValue	oldrv;
							PSObjList::iterator	iter;
							for (iter = l->begin(); iter != l->end(); iter++)
							{
								obj = static_cast <DMBase*> (*iter);
								if (obj->GetProperty (id, oldrv))
								{
									if (obj->SetProperty (id, value))
									{
										if (area)
										{
											area->AddUndoProperty (obj, id, oldrv, value);
											if (obj->GetKind() == PSObject::eObject_Style)
												rep->GetPageComposer()->StyleChanged (static_cast <DMStyle*> (obj));
										}
									}
									else
										result = 1;
								}
								else
									result = 1;
							}
						}
						rep->Modified();
						obj = NULL;
					}
				}
				if (obj != NULL)	// this object
				{
					for (i = 1; i < count; i++)
					{
						PA_Unistring	ustr = PA_GetStringInArray (vals, i);
						RWValue			value;
						value.SetText (RWStr::FromPA (&ustr));
						ustr = PA_GetStringInArray (props, i);
						OSType	id = RW_TextToFourDTypeID (PA_GetUnistring (&ustr), PA_GetUnistringLength (&ustr));
						RWValue	oldrv;
						if (obj->GetProperty (id, oldrv))
						{
							if (obj->SetProperty (id, value))
							{
								if (area)
									area->AddUndoProperty (obj, id, oldrv, value);
							}
							else
								result = 1;
						}
						else
							result = 1;
					}
					if (area != NULL && obj->GetKind() == PSObject::eObject_Style)
						rep->GetPageComposer()->StyleChanged (static_cast <DMStyle*> (obj));
					rep->Modified();
				}
			}
		}
	}

	return result;
}


long RW_GetProperty (long inRepRef, long inRef, FourDTypeID id, PA_Pointer &ptr)
{
	long		result = 0;
	
	try
	{
		DMReport	*rep = DMReport::GetReportObject (inRepRef);
		if (rep == NULL)
			result = errInvalidReportRef;
		else
		{
			DMBase	*obj = rep->GetObject (inRef);
			if (obj == NULL)
				result = errInvalidObjectRef;
			else
			{
				PA_Variable	v = PA_GetPointerValue (ptr);
				RWValue		rv ((RWValue::PA_VariableKind) PA_GetVariableKind (v));
				if (obj->GetProperty (id, rv))
				{
					switch (PA_GetVariableKind (v))
					{
						case eVK_Unistring:
						{
							RWTextValue	tv;
							rv.GetTextValue (tv, NULL);
							PA_Unistring	uni = RWStr::CreatePA (tv);
							PA_SetStringVariable (&v, &uni);
							break;
						}
						case eVK_Real:
							if (rv.CoerceValue (RWValue::eValue_Real))
								PA_SetRealVariable (&v, rv.GetReal());
							else
								result = errInvalidPointerType;
							break;
						case eVK_Longint:
							if (rv.CoerceValue (RWValue::eValue_Integer))
								PA_SetLongintVariable (&v, rv.GetInteger());
							else
								result = errInvalidPointerType;
							break;
						case eVK_Boolean:
							if (rv.CoerceValue (RWValue::eValue_Boolean))
								PA_SetBooleanVariable (&v, rv.GetBoolean());
							else
								result = errInvalidPointerType;
							break;
						case eVK_Blob:
							if (rv.CoerceValue (RWValue::eValue_BLOB))
								PA_SetBlobVariable (&v, rv.GetBlobData(), rv.GetBlobSize());
							else
								result = errInvalidPointerType;
							break;
						case eVK_Picture:
							PA_SetPictureVariable (&v, SR4DData::Get4DPicture (rv));
							break;
						default:
							result = errInvalidPointerType;
							break;
					}
					PA_SetPointerValue (ptr, v);
				}
				else
					result = errGenericError;
			}
		}
	}
	catch (long err)
	{
		result = err;
	}
	catch (...)
	{
		printf ("\nUncaught exception in RW_GetProperty!\n");
		fflush (stdout);
		result = errGenericError;
	}
	
	return result;
}


long RW_SetProperty (long inRepRef, long inRef, FourDTypeID id, PA_Pointer &ptr)
{
	long		result = 0;
	
	try
	{
		DMReport	*rep = DMReport::GetReportObject (inRepRef);
		if (rep == NULL)
			result = errInvalidReportRef;
		else
		{
			DMBase	*obj = NULL;
			if (inRef != 0)
			{
				obj = rep->GetObject (inRef);
				if (obj == NULL)
					result = errInvalidObjectRef;
			}
			if (result == 0)
			{
				OSType	trueID, thisID;
				bool	isStyleProperty = false;
				DMStyle	*st;
				DMArea	*area = NULL;
				if (rep->GetPageComposer() != NULL)
					area = static_cast <DMArea*> (rep);
				switch (id)
				{
					case PSObjPropRelPosTop:
					case PSObjPropRelPosLeft:
					case PSObjPropRelPosBottom:
					case PSObjPropRelPosRight:
					case PSObjPropRelMoveH:
					case PSObjPropRelMoveV:
						trueID = PSObjPropRect;
						break;
					case PSObjPropFontName:
					case PSObjPropSize:
					case PSObjPropStyleF:
					case PSObjPropStyleB:
					case PSObjPropStyleI:
					case PSObjPropStyleU:
					case PSObjPropStyleS:
					case PSObjPropWrap:
					case PSObjPropHorAlign:
					case PSObjPropVertAlign:
					case PSObjPropTextColor:
					case PSObjPropBackColor:
					case PSObjPropRotation:
					case PSObjPropBaseLineShift:
					case PSObjPropHorizontalScale:
					case PSObjPropLineSpacing:
						isStyleProperty = true;
						// fall through
					default:
						trueID = id;
						break;
				}
				if (obj == NULL)	// selected objects
				{
					std::unique_ptr<PSObjList>	l (rep->GetObjects (PSObjPropSelected));
					if (l->size() == 0)
						result = errInvalidObjectRef;
					else if (l->size() == 1)
						obj = static_cast <DMBase*> (*l->begin());
					else if (l->size() > 1)
					{
						PA_Variable	v = PA_GetPointerValue (ptr);
						RWValue		grv;
						switch (PA_GetVariableKind (v))
						{
							case eVK_Unistring:
							{
								PA_Unistring	uni = PA_GetStringVariable (v);
								grv.SetText (RWStr::FromPA (&uni));
								break;
							}
							case eVK_Real:
								grv.SetReal (PA_GetRealVariable (v));
								break;
							case eVK_Longint:
								grv.SetInteger (PA_GetLongintVariable (v));
								break;
							case eVK_Boolean:
								grv.SetBoolean (PA_GetBooleanVariable (v));
								break;
							case eVK_Blob:
							{
								SBlob	data;
								data.Init();
								data.fSize = PA_GetBlobVariable (v, data.fData);
								if (data.fSize > 0)
								{
									data.fData = malloc (data.fSize);
									data.fSize = PA_GetBlobVariable (v, data.fData);
								}
								grv.SetBlob (data, true);
								break;
							}
							case eVK_Picture:
//								SR4DData::GetPictureAsBlobFrom4D (PA_GetPictureVariable (v), grv);
								SR4DData::GetPictureFrom4D (PA_GetPictureVariable (v), grv, false);
								break;
							default:
								result = errInvalidPointerType;
								break;
						}
						PA_ClearVariable (&v);
						if (result == 0)
						{
							RWValue		rv;
							PSObjList::iterator	iter;
							for (iter = l->begin(); iter != l->end(); iter++)
							{
								obj = static_cast <DMBase*> (*iter);
								thisID = trueID;	//mbs 12102010	support for "cloned" Style
								if (isStyleProperty && obj->GetKind() >= PSObject::eObject_Text && (obj->GetKind() <= PSObject::eObject_Fld || obj->GetKind() == PSObject::eObject_TblHdr || obj->GetKind() <= PSObject::eObject_TblCol))
								{
									st = rep->GetStyle (static_cast <DMText*> (obj)->GetStyleID());
									if (st && st->GetFeatures() == 0)
									{
										st = NULL;
										thisID = PSObjPropStyle;
									}
									else if (area && st)
										area->AddUndoSnapshot (st, true);
								}
								else
									st = NULL;
								if (obj->GetProperty (thisID, rv))
								{
									RWValue		oldrv (rv);	//mbs 07122009	make a clone - Text/XMLText is by reference!!!
									if (obj->SetProperty (id, grv))
									{
										if (area != NULL)
										{
											if (obj->GetKind() == PSObject::eObject_Style)
												rep->GetPageComposer()->StyleChanged (static_cast <DMStyle*> (obj));
//											else if (st && st->GetFeatures())
//												rep->GetPageComposer()->StyleChanged (st);
											if (st)
												area->AddUndoSnapshot (st, false);
											else
											{
												if (thisID != id)
													obj->GetProperty (thisID, rv);
												area->AddUndoProperty (obj, thisID, oldrv, rv);
											}
										}
									}
									else
										result = 1;
								}
							}
							obj = NULL;
							rep->Modified();
						}
					}
				}
				if (obj != NULL)	// this object
				{
					RWValue		oldrv1;
					thisID = trueID;	//mbs 12102010	support for "cloned" Style
					if (isStyleProperty && obj->GetKind() >= PSObject::eObject_Text && (obj->GetKind() <= PSObject::eObject_Fld || obj->GetKind() == PSObject::eObject_TblHdr || obj->GetKind() <= PSObject::eObject_TblCol))
					{
						st = rep->GetStyle (static_cast <DMText*> (obj)->GetStyleID());
						if (st && st->GetFeatures() == 0)
						{
							st = NULL;
							thisID = PSObjPropStyle;
						}
						else if (area && st)
							area->AddUndoSnapshot (st, true);
					}
					else
						st = NULL;
					if (obj->GetProperty (thisID, oldrv1))
					{
						RWValue		oldrv (oldrv1);	//mbs 07122009	make a clone - Text/XMLText is by reference!!!
						PA_Variable	v = PA_GetPointerValue (ptr);
						RWValue		rv;
						switch (PA_GetVariableKind (v))
						{
							case eVK_Unistring:
							{
								PA_Unistring	uni = PA_GetStringVariable (v);
								rv.SetText (RWStr::FromPA (&uni));
								break;
							}
							case eVK_Real:
								rv.SetReal (PA_GetRealVariable (v));
								break;
							case eVK_Longint:
								rv.SetInteger (PA_GetLongintVariable (v));
								break;
							case eVK_Boolean:
								rv.SetBoolean (PA_GetBooleanVariable (v));
								break;
							case eVK_Blob:
							{
								SBlob	data;
								data.Init();
								data.fSize = PA_GetBlobVariable (v, data.fData);
								if (data.fSize > 0)
								{
									data.fData = malloc (data.fSize);
									data.fSize = PA_GetBlobVariable (v, data.fData);
								}
								rv.SetBlob (data, true);
								break;
							}
							case eVK_Picture:
//								SR4DData::GetPictureAsBlobFrom4D (PA_GetPictureVariable (v), grv);
								SR4DData::GetPictureFrom4D (PA_GetPictureVariable (v), rv, false);
								break;
							default:
								result = errInvalidPointerType;
								break;
						}
						PA_ClearVariable (&v);
						if (result == 0)
						{
							if (obj->SetProperty (id, rv))
							{
								if (area != NULL)
								{
									if (obj->GetKind() == PSObject::eObject_Style)
										rep->GetPageComposer()->StyleChanged (static_cast <DMStyle*> (obj));
//									else if (st && st->GetFeatures())
//										rep->GetPageComposer()->StyleChanged (st);
									if (st)
										area->AddUndoSnapshot (st, false);
									else
									{
										if (thisID != id)
											obj->GetProperty (thisID, rv);
										if (area->IsRecordingUndo())
											result = area->AddUndoProperty (obj, thisID, oldrv, rv);
									}
									rep->Modified();
								}
							}
							else
								result = errGenericError;
						}
					}
					else
						result = errGenericError;
				}
			}
		}
	}
	catch (long err)
	{
		result = err;
	}
	catch (...)
	{
		printf ("\nUncaught exception in RW_SetProperty!\n");
		fflush (stdout);
		result = errGenericError;
	}
	
	return result;
}


long RW_GetObjects (long inRepRef, long inRef, FourDTypeID id, PA_Variable &outValue)
{
	long		result = 0;
	DMBase		*obj = NULL;

	if (PA_GetVariableKind (outValue) != eVK_ArrayLongint)
		return errInvalidArrayType;

	try
	{
		DMReport	*rep = DMReport::GetReportObject (inRepRef);
		if (rep == NULL)
			result = errInvalidReportRef;
		else
		{
			obj = rep->GetObject (inRef);
			if (obj == NULL)
				result = errInvalidObjectRef;
			else
			{
				std::unique_ptr<PSObjList>	objs (obj->GetObjects (id));
				if (objs.get() == NULL)
					result = errInvalidRequest;
				else
				{
					PA_ResizeArray (&outValue, objs->size());
					for (size_t i = 0; i < objs->size(); i++)
					{
						PA_SetLongintInArray (outValue, i + 1, ((*objs)[i])->GetInternalID() );
					}
				}
			}
		}
	}
	catch (long err)
	{
		result = err;
	}
	catch (...)
	{
		printf ("\nUncaught exception in RW_GetObjects!\n");
		fflush (stdout);
		result = errGenericError;
	}

	return result;
}


long RW_NewObject (long inRepRef, long &outRef, FourDTypeID id, long inParent)
{
	long		result = 0;
	DMBase		*obj = NULL;

	try
	{
//		DMReport	*rep = DMReport::GetReportOfObject (inParent);
		DMReport	*rep = DMReport::GetReportObject (inRepRef);
		if (rep == NULL)
			result = errInvalidReportRef;
		else
		{
			obj = rep->CreateObject (id, inParent, RWXmlNode());
			outRef = obj ? obj->GetInternalID() : 0;
			if (obj)
			{
				if (rep->GetPageComposer() != NULL)
				{
					if (static_cast <DMArea*> (rep)->IsRecordingUndo())
						result = static_cast <DMArea*> (rep)->AddUndoCreate (obj);
					rep->Modified();
				}
			}
		}
	}
	catch (long err)
	{
		result = err;
	}
	catch (...)
	{
		printf ("\nUncaught exception in RW_NewObject!\n");
		fflush (stdout);
		result = errGenericError;
		if (obj)
			delete obj;
	}

	return result;
}


long RW_DeleteObject (long inRepRef, long &ioRef)
{
	long		result = 0;

	try
	{
//		DMBase	*obj = DMReport::GetReportObject (ioRef);
		DMReport	*rep = DMReport::GetReportObject (inRepRef);
		if (rep == NULL)
			result = errInvalidReportRef;
		else
		{
			DMBase	*obj = rep->GetObject (ioRef);
			if (obj == NULL || dynamic_cast <DMArea*> (obj) != NULL)	// must not destoy area!
				result = errInvalidReportRef;
			else
			{
				if (rep->RemoveObject (obj))
				{
					ioRef = 0;
					rep->Modified();
				}
			}
		}
	}
	catch (...)
	{
		printf ("\nUncaught exception in RW_DeleteObject!\n");
		fflush (stdout);
		result = errGenericError;
	}

	return result;
}


long RW_ChangeObjectParent (long inRepRef, long inRef, long inNewRef)
{
	long		result = 0;
	
	try
	{
		//		DMBase	*obj = DMReport::GetReportObject (ioRef);
		DMReport	*rep = DMReport::GetReportObject (inRepRef);
		if (rep == NULL)
			result = errInvalidReportRef;
		else
		{
			DMBase	*obj = rep->GetObject (inRef);
			if (obj == NULL)
				result = errInvalidObjectRef;
			else
			{
				DMBase		*parent = obj->GetParent();
				if (rep->ChangeObjectParent (obj, inNewRef))
				{
					if (rep->GetPageComposer() != NULL)
					{
						if (static_cast <DMArea*> (rep)->IsRecordingUndo())
							result = static_cast <DMArea*> (rep)->AddUndoChangeParent (obj, parent);
						rep->Modified();
					}
				}
				else
					result = errInvalidObjectRef;
			}
		}
	}
	catch (...)
	{
		printf ("\nUncaught exception in RW_ChangeObjectParent!\n");
		fflush (stdout);
		result = errGenericError;
	}
	
	return result;
}


long RW_GetObjectXML (long inRepRef, long inRef, CText &outXML)
{
	long		result = 0;
	
	try
	{
		DMReport	*rep = DMReport::GetReportObject (inRepRef);
		if (rep == NULL)
			result = errInvalidReportRef;
		else
		{
			DMBase	*obj = rep->GetObject (inRef);
			if (obj == NULL)
				result = errInvalidObjectRef;
			else
			{
				RWXmlDocument	xml;
				obj->WriteXML (xml.Node());
				outXML = xml.SaveString (false);
			}
		}
	}
	catch (long err)
	{
		result = err;
	}
	catch (...)
	{
		printf ("\nUncaught exception in RW_GetObjectXML!\n");
		fflush (stdout);
		result = errGenericError;
	}
	
	return result;
}


long RW_NewObjectFromXML (long inRepRef, long &outRef, CText &inXML, long inParent)
{
	long		result = 0;
	DMBase		*obj = NULL;
	
	try
	{
		DMReport	*rep = DMReport::GetReportObject (inRepRef);
		if (rep == NULL)
			result = errInvalidReportRef;
		else
		{
			RWXmlDocument	xml;
			result = LoadSourceXML (xml, inXML, false);
			if (result == noErr)
			{
				obj = rep->CreateObject (xml.Root(), inParent);
				if (obj)
				{
					if (rep->GetPageComposer() != NULL)
					{
						if (static_cast <DMArea*> (rep)->IsRecordingUndo())
							result = static_cast <DMArea*> (rep)->AddUndoCreate (obj);
						rep->Modified();
					}
					outRef = obj->GetInternalID();
				}
			}
		}
	}
	catch (long err)
	{
		result = err;
	}
	catch (...)
	{
		printf ("\nUncaught exception in RW_NewObjectFromXML!\n");
		fflush (stdout);
		result = errGenericError;
		if (obj)
			delete obj;
	}
	
	return result;
}


long RW_FindObjectByID (long inRepRef, CText &inName, long &outRef)
{
//	DMBase		*obj = DMReport::FindObjectByID (inName);
	DMReport	*rep = DMReport::GetReportObject (inRepRef);
	if (rep == NULL)
		return errInvalidReportRef;
	DMBase		*obj = rep->GetObjectByID (inName);
	if (obj == NULL)
		return errInvalidObjectRef;
	outRef = obj->GetInternalID();
	return 0;
}


long RW_GetParent (long inRepRef, long inRef, long &outRef)
{
//	DMBase		*obj = DMReport::FindObject (inRef);
	DMReport	*rep = DMReport::GetReportObject (inRepRef);
	if (rep == NULL)
		return errInvalidReportRef;
	DMBase		*obj = rep->GetObject (inRef);
	if (obj == NULL)
		return errInvalidObjectRef;
	obj = obj->GetParent();
	if (obj == NULL)
		return errInvalidObjectRef;

	outRef = obj->GetInternalID();
	return 0;
}


long RW_GetObjectRect (long inRepRef, long inRef, SRect &outRect)
{
	long		result = 0;
	
	try
	{
		//		DMBase	*obj = DMReport::GetReportObject (ioRef);
		DMReport	*rep = DMReport::GetReportObject (inRepRef);
		if (rep == NULL)
			result = errInvalidReportRef;
		else
		{
			DMBase	*obj = rep->GetObject (inRef);
			if (obj == NULL)
				result = errInvalidObjectRef;
			else
			{
				outRect = obj->GetDrawPosition();
				if (rep->GetPageComposer() != NULL)
					outRect = static_cast <DMArea*> (rep)->MapFromAreaRotated (obj, outRect);
			}
		}
	}
	catch (...)
	{
		printf ("\nUncaught exception in GetObjectRect!\n");
		fflush (stdout);
		result = errGenericError;
	}
	
	return result;
}

long RW_GetEditorRect (long inRepRef, SRect &outRect)
{
	long		result = 0;
	
	try
	{
		DMReport	*rep = DMReport::GetReportObject (inRepRef);
		if (rep == NULL)
			result = errInvalidReportRef;
		else
		{
			if (rep->GetPageComposer() != NULL)
				static_cast <DMArea*> (rep)->GetEditorRect (outRect);
		}
	}
	catch (...)
	{
		printf ("\nUncaught exception in GetEditorRect!\n");
		fflush (stdout);
		result = errGenericError;
	}
	
	return result;
}

long RW_ExecuteScript (long inRepRef)
{
	long		result = 0;
	
	try
	{
		DMReport	*rep = DMReport::GetReportObject (inRepRef);
		if (rep == NULL)
			result = errInvalidReportRef;
		else
		{
			static_cast <DMArea*> (rep)->CallScript(); 
		}
	}
	catch (...)
	{
		printf ("\nUncaught exception in ExecuteScriptInIdle!\n");
		fflush (stdout);
		result = errGenericError;
	}
	
	return result;
}


long RW_SaveUndo (long inRepRef, long inOperation)
{
	long		result = 0;
	
	try
	{
		DMReport	*rep = DMReport::GetReportObject (inRepRef);
		if (rep == NULL)
			result = errInvalidReportRef;
		else
		{
			if (rep->GetPageComposer() != NULL)
				result = static_cast <DMArea*> (rep)->SaveUndo (inOperation, true);
			else
				result = errInvalidObjectRef;
		}
	}
	catch (...)
	{
		printf ("\nUncaught exception in RW_SaveUndo!\n");
		fflush (stdout);
		result = errGenericError;
	}
	
	return result;
}


long RW_AddUndoSnapshot (long inRepRef, long inRef, long inOldState)
{
	long		result = 0;
	
	try
	{
		DMReport	*rep = DMReport::GetReportObject (inRepRef);
		if (rep == NULL)
			result = errInvalidReportRef;
		else
		{
			DMBase	*obj = rep->GetObject (inRef);
			if (obj == NULL)
				result = errInvalidObjectRef;
			else
			{
				if (rep->GetPageComposer() != NULL)
					result = static_cast <DMArea*> (rep)->AddUndoSnapshot (obj, inOldState != 0);
				else
					result = errInvalidObjectRef;
			}
		}
	}
	catch (...)
	{
		printf ("\nUncaught exception in RW_AddUndoSnapshot!\n");
		fflush (stdout);
		result = errGenericError;
	}
	
	return result;
}


long RW_DoUndo (long inRepRef)
{
	long		result = 0;
	
	try
	{
		DMReport	*rep = DMReport::GetReportObject (inRepRef);
		if (rep == NULL)
			result = errInvalidReportRef;
		else
		{
			if (rep->GetPageComposer() != NULL)
				result = static_cast <DMArea*> (rep)->DoEventUndo();
			else
				result = errInvalidObjectRef;
		}
	}
	catch (...)
	{
		printf ("\nUncaught exception in RW_DoUndo!\n");
		fflush (stdout);
		result = errGenericError;
	}
	
	return result;
}


long RW_DoRedo (long inRepRef)
{
	long		result = 0;
	
	try
	{
		DMReport	*rep = DMReport::GetReportObject (inRepRef);
		if (rep == NULL)
			result = errInvalidReportRef;
		else
		{
			if (rep->GetPageComposer() != NULL)
				result = static_cast <DMArea*> (rep)->DoEventRedo();
			else
				result = errInvalidObjectRef;
		}
	}
	catch (...)
	{
		printf ("\nUncaught exception in RW_DoRedo!\n");
		fflush (stdout);
		result = errGenericError;
	}
	
	return result;
}


long RW_PrintSettings (long inRepRef, long inOptions)
{
	long		result = 0;
	
	try
	{
		DMReport	*rep = DMReport::GetReportObject (inRepRef);
		if (rep == NULL)
			result = errInvalidReportRef;
		else
		{
			CText	empty;
			RWValue	prop;
			std::unique_ptr<RWPageComposer> pc (RWPageComposer::CreatePrinterComposer (inOptions & RWPageComposer::eUserFlagsMask, empty, empty));
			RWNativePageComposer	*opc = static_cast <RWNativePageComposer*> (pc.get());
#if	MACVER
			if (inOptions & (RWPageComposer::eUseDefPageSetup | RWPageComposer::eUse4DPageSetup))
				;
			else if (inOptions & RWPageComposer::eValidatePageSetup)
			{
/*
				if (rep->GetPageComposer() != NULL)
					opc->SetPageFormat (static_cast <RWNativePageComposer*> (rep->GetPageComposer())->GetPageFormat());
				else
*/
				{
					if (rep->GetProperty (PSObjPropPageFormat, prop) && prop.GetBlobSize() > 0)
					{
						opc->SetPageFormat (prop.GetBlob());
						prop.Free();
					}
				}
			}

			if (inOptions & (RWPageComposer::eUseDefJobSetup | RWPageComposer::eUse4DJobSetup))
				;
			else if (inOptions & RWPageComposer::eValidateJobSetup)
			{
/*
				if (rep->GetPageComposer() != NULL)
					opc->SetPrintSettings (static_cast <RWNativePageComposer*> (rep->GetPageComposer())->GetPrintSettings());
				else
*/
				{
					if (rep->GetProperty (PSObjPropPrintSettings, prop) && prop.GetBlobSize() > 0)
					{
						opc->SetPrintSettings (prop.GetBlob());
						prop.Free();
					}
				}
			}

			float pageWidth = 0, pageHeight = 0;
			SRect pageMargins;
			result = pc->PrintSettings (pageWidth, pageHeight, pageMargins);
			if (result == noErr)
			{
				Handle			hdl = NULL;
				PMPageFormat	fmt;
				PMPrintSettings	job;
				if (	(inOptions & (RWPageComposer::eUseDefPageSetup | RWPageComposer::eUse4DPageSetup | RWPageComposer::eValidatePageSetup))
					&&	((fmt = opc->GetPageFormat()) != NULL)
					)
				{
//					PMFlattenPageFormat (fmt, &hdl);
//					if (hdl)
//					{
//						HLock (hdl);
//						prop.SetBlob (*hdl, GetHandleSize (hdl), false);
//						rep->SetProperty (PSObjPropPageFormat, prop);
//						HUnlock (hdl);
//						DisposeHandle (hdl);
//						hdl = NULL;
//					}
				}
				if (	(inOptions & (RWPageComposer::eUseDefJobSetup | RWPageComposer::eUse4DJobSetup | RWPageComposer::eValidateJobSetup))
					&&	((job = opc->GetPrintSettings()) != NULL)
					)
				{
//					PMFlattenPrintSettings (job, &hdl);
//					if (hdl)
//					{
//						HLock (hdl);
//						prop.SetBlob (*hdl, GetHandleSize (hdl), false);
//						rep->SetProperty (PSObjPropPrintSettings, prop);
//						HUnlock (hdl);
//						DisposeHandle (hdl);
//					}
				}
				if (pageWidth != 0)
					rep->SetPageMetrics (pageWidth, pageHeight, pageMargins);
			}
#else
//			RWNativePageComposer	*npc = static_cast <RWNativePageComposer*> (rep->GetPageComposer());
			if (inOptions & (RWPageComposer::eUseDefPageSetup | RWPageComposer::eUse4DPageSetup | RWPageComposer::eUseDefJobSetup | RWPageComposer::eUse4DJobSetup))
				;
			else
			{
/*
				if (npc != NULL)
				{
					opc->SetDevMode (npc->GetDevMode(), false);
					opc->SetDeviceNames (npc->GetDeviceNames(), false);
					if ((inOptions & (RWPageComposer::eUseDefPageSetup | RWPageComposer::eUse4DPageSetup)) == 0)
						opc->SetPageSetupDialog (npc->GetPageSetupDialog());
					if ((inOptions & (RWPageComposer::eUseDefJobSetup | RWPageComposer::eUse4DJobSetup)) == 0)
						opc->SetPrintDialog (npc->GetPrintDialog());
				}
				else
*/
				{
					if (rep->GetProperty (PSObjPropDevMode, prop) && prop.GetBlobSize() > 0)
					{
						opc->SetDevMode (prop.GetBlob());
						prop.Free();
					}
					if (rep->GetProperty (PSObjPropDeviceNames, prop) && prop.GetBlobSize() > 0)
					{
						opc->SetDeviceNames (prop.GetBlob());
						prop.Free();
					}
					if ((inOptions & (RWPageComposer::eUseDefPageSetup | RWPageComposer::eUse4DPageSetup)) == 0 && rep->GetProperty (PSObjPropPageSetupDlg, prop) && prop.GetBlobSize() > 0)
					{
						opc->SetPageSetupDialog (prop.GetBlob());
						prop.Free();
					}
					if ((inOptions & (RWPageComposer::eUseDefJobSetup | RWPageComposer::eUse4DJobSetup)) == 0 && rep->GetProperty (PSObjPropPrintDlg, prop) && prop.GetBlobSize() > 0)
					{
						opc->SetPrintDialog (prop.GetBlob());
						prop.Free();
					}
				}
			}

			float pageWidth = 0, pageHeight = 0;
			SRect pageMargins;
			result = opc->PrintSettings (pageWidth, pageHeight, pageMargins);
			if (result == noErr)
			{
				HGLOBAL	hg = opc->GetDevMode();
				if (hg)
				{
					prop.SetBlob (GlobalLock (hg), GlobalSize (hg), false);
					rep->SetProperty (PSObjPropDevMode, prop);
					prop.Free();
					GlobalUnlock (hg);
				}
				hg = opc->GetDeviceNames();
				if (hg)
				{
					prop.SetBlob (GlobalLock (hg), GlobalSize (hg), false);
					rep->SetProperty (PSObjPropDeviceNames, prop);
					prop.Free();
					GlobalUnlock (hg);
				}
				if (inOptions & (RWPageComposer::eUseDefPageSetup | RWPageComposer::eUse4DPageSetup | RWPageComposer::eValidatePageSetup))
				{
					PAGESETUPDLGW	*ps = opc->GetPageSetupDialog();
					prop.SetBlob (ps, ps? sizeof (*ps): 0, false);
					rep->SetProperty (PSObjPropPageSetupDlg, prop);
					prop.Free();
				}
				if (inOptions & (RWPageComposer::eUseDefJobSetup | RWPageComposer::eUse4DJobSetup | RWPageComposer::eValidateJobSetup))
				{
					PRINTDLGW	*pd = opc->GetPrintDialog();
					prop.SetBlob (pd, pd? sizeof (*pd): 0, false);
					rep->SetProperty (PSObjPropPrintDlg, prop);
					prop.Free();
				}
				if (pageWidth != 0)
					rep->SetPageMetrics (pageWidth, pageHeight, pageMargins);
			}
#endif
		}
	}
	catch (...)
	{
		printf ("\nUncaught exception in RW_PrintSettings!\n");
		fflush (stdout);
		result = errGenericError;
	}
	
	return result;
}



long RW_AddRemoveStyle (PA_PluginParameters params, bool inAdd)
{
// eTextStyleAdd:			//	outStr, inStr, from, to, style, fontName, fontSize, fontColor, setColor, scale, rounding, mode
// eTextStyleRemove:		//	outStr, inStr, from, to, style, fontName, fontSize, fontColor, setColor, scale, rounding,
	sBuf = PA_GetStringParameter (params, 2);
	CText	s2 = RWStr::FromPA (sBuf);					// inStr
	sBuf = PA_GetStringParameter (params, 6);
	CText	s6 = RWStr::FromPA (sBuf);					// fontName
	RWSpan span (	PA_GetLongParameter (params, 3) - 1,								// from - passed value is 1-based
					PA_GetLongParameter (params, 4) - PA_GetLongParameter (params, 3),	// to
					PA_GetLongParameter (params, 5),									// style
					PA_GetDoubleParameter (params, 7),									// fontSize
					s6,																	// fontName
					(unsigned long) PA_GetLongParameter (params, 8),					// fontColor
					0 != PA_GetLongParameter (params, 9));								// setColor
	RW4DStyledText text (s2);
	if (inAdd)
	{
		text.AddSpan (span, PA_GetLongParameter (params, 12));
		text.Scale (PA_GetDoubleParameter (params, 10), PA_GetLongParameter (params, 11));
	}
	else
	{
		text.Scale (PA_GetDoubleParameter (params, 10), PA_GetLongParameter (params, 11));
		text.RemoveSpan (span);
	}
	text.Clean();
	s6 = text.toXMLString();
	sBuf = PA_GetStringParameter (params, 1);
	RWStr::SetPA (sBuf, s6);
	return 0;
}


long RW_ApplyStyle (PA_PluginParameters params)
{
// eTextStyleAddStyle:		//	outStr, inStr, from, to, inRepRef, styleID, scale, rounding
	DMReport	*rep = DMReport::GetReportObject (PA_GetLongParameter (params, 5));
	if (rep == NULL)
		return errInvalidReportRef;

	DMStyle		*style = rep->GetStyle (PA_GetLongParameter (params, 6));
	if (style == NULL)
		return errInvalidObjectRef;

	sBuf = PA_GetStringParameter (params, 2);
	CText	s2 = RWStr::FromPA (sBuf);					// inStr
	sBuf = PA_GetStringParameter (params, 6);
	CText	s6 (style->GetFName());
	SRGBColor c = style->GetTextColor();
	RWSpan span (	PA_GetLongParameter (params, 3) - 1,								// from - passed value is 1-based
					PA_GetLongParameter (params, 4) - PA_GetLongParameter (params, 3),	// to
					style->GetStyle(),													// style
					style->GetSize(),													// fontSize
					s6,																	// fontName
					(unsigned long) c,													// fontColor
					true);																// setColor
	RW4DStyledText text (s2);
	text.AddSpan (span, RWSpan::mode_add);
	text.Scale (PA_GetDoubleParameter (params, 7), PA_GetLongParameter (params, 8));
	text.Clean();
	s6 = text.toXMLString();
	sBuf = PA_GetStringParameter (params, 1);
	RWStr::SetPA (sBuf, s6);
	return 0;
}

#if	!MACVER
int CALLBACK EnumFontFamExProc( const LOGFONTW *lpelfe, const TEXTMETRICW *lpntme, DWORD FontType, LPARAM lParam )
{
	if (wcscmp (&gLastFontName[0], &(lpelfe->lfFaceName[0]))) {
		PA_Variable * outValue = (PA_Variable *)lParam;
		long i = PA_GetArrayNbElements (*outValue) + 1;
		PA_ResizeArray (outValue, i);
		PA_Unichar *data = (PA_Unichar *) &(lpelfe->lfFaceName);
		PA_Unistring uniString = PA_CreateUnistring(data);
				
		PA_SetStringInArray (*outValue, i,&uniString);
		wcscpy (&gLastFontName[0], &(lpelfe->lfFaceName[0]));
	}
	return 1;
}
#endif


long  RW_GetFonts (PA_Variable &outValue) 
{
	if (PA_GetVariableKind (outValue) != eVK_ArrayUnicode)
		return errInvalidArrayType;
	
#if	MACVER
 	
	CTFontCollectionRef collection = CTFontCollectionCreateFromAvailableFonts(NULL);
	if (collection) {
		CFArrayRef array = CTFontCollectionCreateMatchingFontDescriptors(collection);
		CFIndex arrayNum = CFArrayGetCount(array);
		
		PA_ResizeArray (&outValue, arrayNum);
		
		for (CFIndex i = 0; i < arrayNum; i++) {
			CFStringRef attribute = (CFStringRef)CTFontDescriptorCopyAttribute( (CTFontDescriptorRef)CFArrayGetValueAtIndex(array, i), kCTFontDisplayNameAttribute);
			
			int strLen = CFStringGetLength(attribute);
			
			PA_Unichar *data = (PA_Unichar *) malloc(strLen * sizeof(PA_Unichar) + 1);
			
			CFStringGetCharacters (attribute, CFRangeMake(0, strLen), data);
			data[strLen] = 0;
			PA_Unistring uniString = PA_CreateUnistring(data);
			
			PA_SetStringInArray (outValue, i + 1,&uniString);
			
			free (data);
			CFRelease(attribute);
		}
		
		CFRelease(array);
		CFRelease(collection);
	}
#else
	
	gLastFontName[0] = 0;
	LOGFONTW lf;
	lf.lfFaceName[0] = '\0';
	lf.lfCharSet = DEFAULT_CHARSET;
	HDC hDC = ::GetDC(NULL);
	EnumFontFamiliesExW(hDC, &lf, (FONTENUMPROCW) &EnumFontFamExProc, (long)&outValue, 0);
	ReleaseDC(NULL, hDC);
#endif	
	return 0;
}


