/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : t1
 #	author : mbs
 #	16.09.2004
 #
 # --------------------------------------------------------------------------------*/


enum
{
	eFirst	= 0,

	eRegister,				// RW_Register(&T):L
	eRWArea,				// %ReportWriter

	eNewReport,				// RW_NewReport(&L;&T;&L):L
	eParseReport,			// RW_ParseReport(&L;&T;&L):L
	eSaveReport,			// RW_SaveReport(&L;&T;&L):L
	eDeleteReport,			// RW_DeleteReport(&L):L

	eGetProperties,			// RW_GetProperties(&L;&L;&Y;&Y;&Y):L
	eSetProperties,			// RW_SetProperties(&L;&L;&Y;&Y):L
	eGetProperty,			// RW_GetProperty(&L;&L;&T;&Z):L
	eSetProperty,			// RW_SetProperty(&L;&L;&T;&Z):L
	eGetObjects,			// RW_GetObjects(&L;&L;&T;&Y):L

	eNewObject,				// RW_NewObject(&L;&L;&T;&L):L
	eDeleteObject,			// RW_DeleteObject(&L;&L):L
	eChangeObjectParent,	// RW_ChangeObjectParent(&L;&L;&L):L
	eGetObjectXML,			// RW_GetObjectXML(&L;&L;&T):L
	eNewObjectFromXML,		// RW_NewObjectFromXML(&L;&L;&T;&L):L

	eFindObjectByID,		// RW_FindObjectByID(&L;&T;&L):L
	eGetParent,				// RW_GetParent(&L;&L;&L):L
	eGetObjectRect,			// RW_GetObjectRect(&L;&L;&8;&8;&8;&8):L

	eSaveUndo,				// RW_Area_SaveUndo(&L;&L):L
	eAddUndoSnapshot,		// RW_Area_AddUndo(&L;&L;&L):L
	eDoUndo,				// RW_Area_Undo(&L):L
	eDoRedo,				// RW_Area_Redo(&L):L

	ePrintSettings,			// RW_PrintSettings(&L;&L):L

	eOpenSession,			// RW_OpenSession(&L;&L;&T;&T;&T;&T):L
	eCloseSession,			// RW_CloseSession(&L):L
	ePrintSRP,				// RW_Print(&T;&L;&L;&T;&L;&T):L
	eProcessSRP,			// RW_Process_RW(&T;&L;&T):L
	ePrintRW,				// RW_Print_RW(&T;&L;&L;&T;&L;&T):L

	eColorPicker_Removed,	// was RW_ColorPicker(&L):L - removed, 4D has Select RGB color; slot kept so later command numbers do not change

	eTextStyleAdd,			// RW_AddStyle(&T;&T;&L;&L;&L;&T;&8;&L;&L;&8;&L;&L):L
	eTextStyleRemove,		// RW_RemoveStyle(&T;&T;&L;&L;&L;&T;&8;&L;&L;&8;&L):L
	eTextStyleAddStyle,		// RW_ApplyStyle(&T;&T;&L;&L;&L;&L;&8;&L):L
	eTokenize,				// RW_Tokenize(&T;&O):L
	eDetokenize,			// RW_Detokenize(&O):T
	eRunScript,				// RW_RunScript(&T)
	eVersionString,			// RW_GetVersion:T
	
	eGetEditorRect,			// RW_GetEditorRect(&L;&8;&8;&8;&8):L
	eSetScriptExecution,	// RW_ExecuteScript(&L):L
	
	eGetFonts,				// RW_GetFonts(&Y):L

	// report definition as JSON (RWXmlJson.h) - the same document as the XML of RW_ParseReport / RW_SaveReport
	eParseReportJSON,		// RW_ParseReportJSON(&L;&T;&L):L	ref, JSON text or file path (options bit 0), options
	eSaveReportJSON,		// RW_SaveReportJSON(&L;&T;&L):L	ref, JSON text or file path (options bit 0), options (bit 1: indented text)
	eParseReportObject,		// RW_ParseReportObject(&L;&J):L	ref, 4D object
	eSaveReportObject,		// RW_SaveReportObject(&L):J		ref; returns the report as a 4D object (empty object on error)

	eLast
};

enum
{
	errGenericError		= -1L,
	errNone,
	errCantLoadXML,
	errCantSaveXML,
	errInvalidReportRef,
	errInvalidObjectRef,
	errInvalidRequest,
	errInvalidArrayType,
	errInvalidPointerType,
	errInvalidSessionRef,
	errCantLoadJSON,		// 9: JSON syntax error, not a report document, file not readable
	errCantSaveJSON,		// 10: file not writable
	errInvalidObject,		// 11: Null object passed
	errUserCanceled = -128
};

typedef	OSType	FourDTypeID;
FourDTypeID	RW_TextToFourDTypeID (PA_PluginParameters params, int index);
FourDTypeID RW_TextToFourDTypeID (PA_Unichar* p, long l);
PA_Unichar* RW_FourDTypeIDToText (OSType l);

void InitPlugin();
void DeinitPlugin();

long RW_OpenSession (long &outSession, long dstFlags, RWString &dst, RWString &inTemplate, RWString &job, RWString &inPrinter);	//mbs 25072011	printer
long RW_CloseSession (long &ioSession);
long RW_Print (RWString &src, long inOptions, long dstFlags, RWString &dst, long inSession, RWString &inPrinter);	//mbs 25072011	printer
long RW_Process_RW (RWString &src, long inOptions, RWString &dst);
long RW_Print_RW (RWString &src, long inOptions, long dstFlags, RWString &dst, long inSession, RWString &inPrinter);	//mbs 25072011	printer


void RW_Area (PA_PluginParameters params);

long RW_CreateReport (long &outRepRef, RWString &src, long inOptions);
long RW_ParseReport (long inRepRef, RWString &src, long inOptions);
long RW_SaveReport (long inRepRef, RWString &dst, long inOptions);
long RW_DeleteReport (long &ioRepRef);
long RW_ParseReportJSON (long inRepRef, RWString &src, long inOptions);
long RW_SaveReportJSON (long inRepRef, RWString &dst, long inOptions);

long RW_GetProperties (PA_PluginParameters params);	// inRepRef, inRef, PA_Variable &ioProps, PA_Variable &ioValues);
long RW_SetProperties (PA_PluginParameters params);	// inRepRef, inRef, PA_Variable &inProps, PA_Variable &inValues);
long RW_GetProperty (long inRepRef, long inRef, FourDTypeID id, PA_Pointer &ptr);
long RW_SetProperty (long inRepRef, long inRef, FourDTypeID id, PA_Pointer &ptr);
long RW_GetObjects (long inRepRef, long inRef, FourDTypeID id, PA_Variable &ioValue);

long RW_NewObject (long inRepRef, long &outRef, FourDTypeID id, long inParent);
long RW_DeleteObject (long inRepRef, long &ioRef);
long RW_ChangeObjectParent (long inRepRef, long inRef, long inNewRef);
long RW_GetObjectXML (long inRepRef, long inRef, RWString &outXML);
long RW_NewObjectFromXML (long inRepRef, long &outRef, RWString &inXML, long inParent);

long RW_FindObjectByID (long inRepRef, RWString &inName, long &outRef);
long RW_GetParent (long inRepRef, long inRef, long &outRef);
long RW_GetObjectRect (long inRepRef, long inRef, SRect &outRect);

long RW_SaveUndo (long inRepRef, long inOperation);
long RW_AddUndoSnapshot (long inRepRef, long inRef, long inOldState);
long RW_DoUndo (long inRepRef);
long RW_DoRedo (long inRepRef);

long RW_PrintSettings (long inRepRef, long inOptions);

long RW_AddRemoveStyle (PA_PluginParameters params, bool inAdd);
long RW_ApplyStyle (PA_PluginParameters params);

long RW_GetEditorRect (long inRepRef, SRect &outRect);
long RW_ExecuteScript (long inRepRef);

long  RW_GetFonts (PA_Variable &outValue);
#if	!MACVER
int CALLBACK EnumFontFamExProc( const LOGFONTW *lpelfe, const TEXTMETRICW *lpntme, DWORD FontType, LPARAM lParam );
#endif
