/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-ReportWriter.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : ReportWriter
 #	author : INFORCE sro
 #	31.10.2023
 #  
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-ReportWriter.h"

#pragma mark -

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
	try
	{
        switch(selector)
        {
			// --- ReportWriter
            
			case 1 :
				My_First_Plugin_Command(params);
				break;

        }

	}
	catch(...)
	{

	}
}

#pragma mark -

void My_First_Plugin_Command(PA_PluginParameters params) {

}

