/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-ReportWriter.h
 #	source generated by 4D Plugin Wizard
 #	Project : ReportWriter
 #	author : INFORCE sro
 #	31.10.2023
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_REPORTWRITER_H
#define PLUGIN_REPORTWRITER_H

#include "4DPluginAPI.h"

#pragma mark -

void My_First_Plugin_Command(PA_PluginParameters params);

#endif /* PLUGIN_REPORTWRITER_H */
